apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::279272046356:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QKTB4T3HSZY5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::279272046356:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-24T18:39:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2484"
  uid: 96c18236-75b6-4a0b-b528-1c91fa0924dd
