apiVersion: v1
data:
  mapRoles: |
    - groups:
       - system:masters
       rolearn: arn:aws:iam::279272046356:role/UdacityFlaskDeployCBKubectlRole
       username: build

     - groups:
       - system:bootstrappers
       - system:nodes
       rolearn: arn:aws:iam::279272046356:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-AO9MWCYLEJMM
       username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-13T17:28:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1421"
  uid: 58f4f439-6de0-4aa5-bb42-b1caead88a91
