apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::279272046356:role/UdacityFlaskDeployCBKubectlRole
      username: build   
      
    - groups:
      - system:masters
      arn:aws:iam::279272046356:role/myFinalStack-CodeBuildServiceRole-WKCCG4MHBFJ4
      username: myFinalStack-CodeBuildServiceRole-WKCCG4MHBFJ4   
         
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::279272046356:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JMYX41E0G3ZP
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-14T11:08:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1405"
  uid: 5c9b2902-8a2d-47aa-b9d8-726d1616e299
